redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis

test: *redis

production: *redis

  # adapter: redis
  # url: redis://localhost:6379/1
  # channel_prefix: prueba_production
