# redis: &redis
#   adapter: redis
#   url: redis://localhost:6379/1
#
# development: *redis
#
# test: *redis
#
# production:
#   adapter: redis
#   url: <%= ENV["REDISCLOUD_URL"]%>


development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: redis://h:p58e9b1123b6dd822e675718b46721e0d65998cdd0f42d168ba0f5d1c305a8a12@ec2-52-55-90-143.compute-1.amazonaws.com:49459
  :host: ec2-52-55-90-143.compute-1.amazonaws.com
  :port: 49459
  :password: p58e9b1123b6dd822e675718b46721e0d65998cdd0f42d168ba0f5d1c305a8a12
  :inline: true
  :timeout: 1
